---
- id: yamkix
  name: Format yaml files with Yamkix
  description: This hook formats YAML files using Yamkix.
  entry: yamkix
  language: python
  types: [yaml]
  pass_filenames: true
  args: [--silent]
