---
site_name: Yamkix
site_url: https://looztra.github.io/yamkix/
site_description: Yamkix is an opinionated yaml file formatter.
repo_url: https://github.com/looztra/yamkix
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.copy

validation:
  omitted_files: warn
  absolute_links: warn # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn # New in MkDocs 1.6

markdown_extensions:
  - toc:
      permalink: true
  - sane_lists
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [std, py]
          options:
            docstring_style: google
            separate_signature: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            extensions:
              - griffe_pydantic:
                schema: true
              - griffe_typingdoc
              - griffe_warnings_deprecated
  - git-revision-date-localized:
      enable_creation_date: false
      type: iso_datetime
nav:
  - Introduction: index.md
  - Configuration: configuration.md
  - Install: install.md
  - Usage: usage.md
  - Public API Reference: reference.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Pointers: pointers.md
watch:
  - src
