extend = "ruff_defaults.toml"
# you can change this file, you should NOT remove the extend directive

[lint]

ignore = [
]
per-file-ignores."**/tests/*" = [
    "INP001", # INP001: File {filename} is part of an implicit namespace package. Add an __init__.py.
    "S101",   # S101: Use of assert detected. Hey man, we do need asserts in pytest tests.
]
per-file-ignores."experiments/*" = [
    "T201", # Print statements
]
