extend = "ruff_defaults.toml"
# you can change this file, you should NOT remove the extend directive

[lint]

ignore = [
    "PT009",
    "PT027",
    "ANN001",
    "ANN201",
    "TC002",
    "T201",
    "C408",
    "PTH113",
    "PTH123",
    "PERF402",
    "SIM102",
    "SIM108",
    "SIM118",
    "EM102",
    "PLR0912",
    "PLR0913",
    "TRY003",
]
